/**
 * Serves AVIF, then WebP, then JPEG from the variants generated by
 * scripts/optimize-media.mjs into /public/img.
 *
 * width and height are required rather than optional: without an intrinsic
 * aspect ratio the browser cannot reserve space before the image loads, and
 * every image on the page contributes to Cumulative Layout Shift.
 */

interface Props {
  /** Base name of the generated variants, e.g. "about" for /img/about-800.avif */
  name: string;
  alt: string;
  widths: number[];
  /** The `sizes` attribute; get this right or srcset cannot pick correctly. */
  sizes: string;
  width: number;
  height: number;
  className?: string;
  /** Only the LCP image should be eager; everything else stays lazy. */
  priority?: boolean;
  /** Skip AVIF/WebP sources when only JPEG variants exist (e.g. video posters). */
  jpgOnly?: boolean;
}

export default function ResponsiveImage({
  name,
  alt,
  widths,
  sizes,
  width,
  height,
  className,
  priority = false,
  jpgOnly = false,
}: Props) {
  const srcSet = (ext: string) =>
    widths.map((w) => `/img/${name}-${w}.${ext} ${w}w`).join(', ');

  const fallbackWidth = widths[widths.length - 1];

  if (jpgOnly) {
    return (
      <img
        src={`/img/${name}-${fallbackWidth}.jpg`}
        alt={alt}
        width={width}
        height={height}
        className={className}
        loading={priority ? 'eager' : 'lazy'}
        decoding={priority ? 'sync' : 'async'}
        fetchpriority={priority ? 'high' : 'auto'}
      />
    );
  }

  return (
    <picture>
      <source type="image/avif" srcSet={srcSet('avif')} sizes={sizes} />
      <source type="image/webp" srcSet={srcSet('webp')} sizes={sizes} />
      <img
        src={`/img/${name}-${fallbackWidth}.jpg`}
        srcSet={srcSet('jpg')}
        sizes={sizes}
        alt={alt}
        width={width}
        height={height}
        className={className}
        loading={priority ? 'eager' : 'lazy'}
        decoding={priority ? 'sync' : 'async'}
        // React 18 only accepts the lowercase HTML attribute, not fetchPriority.
        fetchpriority={priority ? 'high' : 'auto'}
      />
    </picture>
  );
}
